### ISSUE TITLE
How to add support for decorators?

### ISSUE THREAD

**Issue by hillscottc** [jake-wies/webpack-hotplate#3]
Great boilerplate. I'm going to use this at Disney, if I can make this work. Here's the issue:

I'm using mobx, and that requires decorators. I npm installed `babel-plugin-transform-decorators-legacy`, and added it To my `.babelrc` like:
```
 "plugins": ["transform-decorators-legacy"]
```

But LINT is failing to recognize the decorators. IIs it because of all the 'run-first' stuff in the webpack.config?
```
// make ESLint run first
enforce: 'pre',
use: [
// eslint runs before babel
{
loader: 'eslint-loader',
options: options     // eslint-disable-line object-shorthand
}
```
How do I make lint recognize the decorators?

**Comment by hillscottc** [comment]
Hmm. It's not just an eslint thing. When I disable linting, it actually fails to compile at the decorators.
```
 class SearchStore {
> 19 |   @observable statusOptions = [];
  22 | }
Module build failed: SyntaxError: Unexpected token (19:28)
```
The token its complaining about is the `@` decorator.

**Comment by jake-wies** [comment]
Hey @hillscottc,

Glad you're getting some real world use out of this project! I've been thinking over the idea of adding state management support into **webpack-hotplate** so this issue is coming up at a good time.

I don't have much experience with mobX. I ran by this [GitHub issue](https://github.com/facebookincubator/create-react-app/issues/214) regarding decorators when doing some quick Google searches regarding ESLint and mobX:

> For people coming to this thread later—if you use MobX or a similar library, you don’t need decorators. They are just syntax sugar in this case.

Maybe this is something you already know and you've decided to use decorators anyway. If this is the case, there is a possible solution using [babel-eslint](https://github.com/babel/babel-eslint). I found reference to `babel-eslint` in [this GitHub issue](https://github.com/mobxjs/mobx/issues/629), which seems to be referencing your issue as well:

> `babel-eslint` is needed for decorator support

Adopting `babel-eslint` may require some slight adjustment to `.eslintrc.json`. I'm currently at work now but when I get home tonight I'll continue to work on the issue. For now, take a look at `babel-eslint` and see if it may solve your issue.

**Comment by hillscottc** [comment]
Cool. Good news is, I've got it compiling now. Turns out I needed `transform-class-properties` as well. So, this:
```
  "plugins": [
    "transform-class-properties",
    "transform-decorators-legacy"
  ]
```

**Comment by hillscottc** [comment]
Linting still complains though. I see your point about `babel-eslint`. Fiddling....

**Comment by hillscottc** [comment]
Why the effort to make eslint run ***before*** Babel? I don't recall doing that in Webpack 1.2, where I've used MobX. Could that be the problem?

**Comment by hillscottc** [comment]
Argh. Though it compiles, it isn't handling the observables properly. `Parsing error: Unexpected character '@'`
So it's not just the linting. Would be awesome if you could get MobX working with this boilerplate. Mobx has a [webpack 1.2 boilerplate](https://github.com/mobxjs/mobx-react-boilerplate)

**Comment by jake-wies** [comment]
Using: `enforce: 'pre'` ensures that ESLint does it thing before anything else processes. My guess is that ESLint is erroring out because it doesn't know what to make of the **@** in your decorator.

Because of this, the only solutions I'm currently seeing to get ESLint to stop complaining is to reconfigure ESLint in your project with `babel-eslint` or not use decorators.

**Comment by jake-wies** [comment]
The [webpack 1.2 boilerplate](https://github.com/mobxjs/mobx-react-boilerplate) you referenced is using `babel-eslint`:

Check out their [.eslintrc](https://github.com/mobxjs/mobx-react-boilerplate/blob/master/.eslintrc).

```json
"parser": "babel-eslint",
```

**Comment by hillscottc** [comment]
Ah, that may have helped. Added `"parser": "babel-eslint" to your .eslintrc.json. Checking.

**Comment by jake-wies** [comment]
Doing some more digging through ESLint docs.

Here is a [good section](http://eslint.org/docs/user-guide/configuring#specifying-parser) about adding custom parsers.

**Comment by hillscottc** [comment]
Woohoo! That seemed to work. So to summarize, I did:
```
$ npm install --save-dev babel-preset-stage-0 transform-decorators-legacy babel-plugin-transform-decorators-legacy babel-eslint
```
In my `.babelrc`
```
{
  "presets": [
    [ "es2015", { "modules": false } ],
    "stage-0",
    "react"
  ],
  "plugins": [
    "transform-class-properties",
    "transform-decorators-legacy"
  ]
}
```
And in `eslintrc.json`
```
"parser": "babel-eslint",
```

**Comment by jake-wies** [comment]
Awesome! So basically you needed to satisfy both Babel and ESLint? 

Glad to have helped!

**Comment by jake-wies** [comment]
Going to close this issue but please re-open if needed @hillscottc 😄

**Comment by hillscottc** [comment]
I'm not sure this is working properly yet. No console errs, but my observed properties seem to be null. But this may be because I used MobX improperly. Don't know for sure yet.

**Comment by jake-wies** [comment]
Ok I'll reopen the issue. Keep me updated.

**Comment by hillscottc** [comment]
Will do. :)

**Comment by hillscottc** [comment]
It may be a few days before I get back to this, sorry.

**Comment by jake-wies** [comment]
No rush @hillscottc !

**Comment by hillscottc** [comment]
No, seems my observed properties are not updating properly. No visible decorator errors...just no MobX goodness.

**Comment by jake-wies** [comment]
So, just to be clear, the issue you're having is ESLint not recognizing mobX's decorator syntax?

**Comment by hillscottc** [comment]
No, I seem to have that solved. There are no visible errors in esLint or console. I'm going to try again with a basic MobX example. It may be that I'm I've made some other error.

**Comment by jake-wies** [comment]
Any luck? 

Going to sit down tomorrow at work for a bit and see if I can wrap my head around this a bit more. I've stepped away from **webpack-hotplate** for a few days because of another project outside of the React scope, but excited to jump back in soon.

**Comment by jake-wies** [comment]
@hillscottc Same with this issue. Please reopen if you're still actively using the project and want to revisit.
